# To create the conda environment, run:
#   conda env create -f environment.yml
name: mnist-digit-classifier
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.13.2
  - pytorch=2.6
  - torchvision=0.21.0
  - streamlit=1.44.0
  - psycopg=3.2.6
  - scikit-learn=1.6.1
  - fastapi=0.112.2
